tasks:
  default:
    onboard_world: MessengerBotChatOnboardWorld
    task_world: MessengerBotChatTaskWorld
    timeout: 9999999999999
    agents_required: >1
task_name: chatbot
world_module: parlai.chat_service.services.browser_chat.worlds
overworld: MessengerOverworld
max_workers: 30
opt:
  debug: True
  models:
    blender_90M:
      model: transformer/generator
      model_file: zoo:blender/blender_90M/model
      interactive_mode: True
      no_cuda: False
additional_args:
  page_id: 1 # Configure Your Own Page
